config/routes.rb
Rails.application.routes.draw do

  root 'superheros#index'

  resources :superheros

end

app/models/superhero.rb
class Superhero < ActiveRecord::Base

	def has_cape
		self.cape ? "Yes" : "No"
	end

end

app/controllers/superheros_controller.rb
class SuperherosController < ApplicationController

	def index
		@superheros = Superhero.all
	end

	def show
		@superhero = Superhero.find(params[:id])
	end

	def new
		@superhero = Superhero.new
	end

	def edit
		@superhero = Superhero.find(params[:id])
	end

	def update
		@superhero = Superhero.find(params[:id])
		@superhero.update_attributes(superhero_params)
		if @superhero.save
			redirect_to superhero_path(@superhero.id)
		else
			redirect_to superheros_path
		end
	end

	def create
		@superhero = Superhero.new(superhero_params)
		if @superhero.save
			redirect_to superhero_path(@superhero.id)
		else
			redirect_to superheros_path
		end
	end

	def destroy
		@superhero = Superhero.find(params[:id])
		@superhero.destroy
	end

	private

	def superhero_params
		params.require(:superhero).permit(:name, :cape, :superpower, :image)
	end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Superheros</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="top-half">
	<div class="header">
		<h2>Superheroes App</h2>
	</div>
	<div class="navbar">
		<ul>
			<li><%= link_to "Create New Hero", new_superhero_path %></li>
		</ul>
	</div>
	</div>
	<div class="shade">
	</div>
	<div class="content">
	<%= yield %>
	</div>

</body>
</html>

app/views/superheros/_form.html.erb
<%= form_for @superhero do |s| %>
	<p>
		<%= s.label :name %>
		<%= s.text_field :name %>
	</p>
	<p>
		<%= s.label "Cape" %>
		<%= s.radio_button :cape, true %>
		<%= s.label "No Cape" %>
		<%= s.radio_button :cape, false %>
	</p>
	<p>
		<%= s.label :super_power %>
		<%= s.text_area :super_power %>
	</p>
	<p>
		<%= s.label :image %>
		<%= s.text_field :image %>
	</p>
	<p>
		<%= s.submit %>
	</p>

<% end %>

app/views/superheros/edit.html.erb
<h2>Edit <%= @superhero.name %></h2>

<%= render 'form' %>

app/views/superheros/index.html.erb
<h2>Heroes</h2>
<ul>
	<% @superheros.each do |s| %>
	<li class="index"><%= image_tag(s.image, size: "100") %>
	<p><%= link_to s.name, superhero_path(s.id) %> <%= link_to "Edit", edit_superhero_path(s.id) %> <%= link_to "Delete", superheros_path, method: :delete %></p></li>
	<% end %>
</ul>

app/views/superheros/new.html.erb
<h2>Create Your Hero!</h2>

<%= render 'form' %>

app/views/superheros/show.html.erb
<h2><%= @superhero.name %></h2>
<%= image_tag(@superhero.image, size: "150") %>
<p>Attributes:</p>
<ul>
	<li>Cape: <%= @superhero.has_cape %></li>
	<li>Power: <%= @superhero.super_power %></li>
</ul>

<%= link_to "Back to Superheroes", superheros_path %>